ALTER TABLE repos
  ADD COLUMN IF NOT EXISTS pushed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS archived BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS open_issues_count INT,
  ADD COLUMN IF NOT EXISTS created_at_gh TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS latest_release_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_repos_pushed_at ON repos (pushed_at DESC NULLS LAST);
